New landing page
ayotidapo/efiko_kids pull request #6
Opened 2023-09-07 10:03 UTC by victory-nwawunze

I just created the landing page, and It is 100% responsive.

2023-09-07 10:38 UTC, onyegood commented on public/assets/tumbs up 1.svg
Assets file must not have space in its name, remove spaces and name it properly

2023-09-07 10:41 UTC, onyegood commented on public/assets/facebook icon.svg
This asset should be called facebook, remove the space and icon.

2023-09-07 11:31 UTC, onyegood commented on common/mobileApp/index.tsx
> +                  {/* <Image src='/assets/google.svg' width={20} height={20} /> */}
What is this comment doing here?

2023-09-07 11:31 UTC, onyegood commented on common/mobileApp/index.tsx
> +            {/* Img */}
What is this comment doing here?

2023-09-07 11:31 UTC, onyegood commented on common/Footer/index.tsx
> +            <div className='mt-[15%] flex items-center'>
Create a component called `SocialMedia` and pull all social media icons there.

2023-09-07 11:31 UTC, onyegood commented on common/Footer/index.tsx
> +                <Image src='/assets/instagram.svg' width={60} height={40} alt='instagram' />
Make this a reusable component

2023-09-07 11:31 UTC, onyegood commented on common/Footer/Footer.scss
We must not hardcode color anywhere in the app. Also please remove `!important` anywhere you have it in your CSS file.

2023-09-07 11:31 UTC, onyegood commented on common/Banner/banner.scss
> +  /* .pl-30 {
Remove this comment

2023-09-07 11:31 UTC, onyegood commented on common/Desc/Desc.scss
> +  /* spacing {
Remove commented block

2023-09-07 11:31 UTC, onyegood commented on common/Desc/index.tsx
> +            {/* We are majorly focused on <br /> <span className=' font-bold'>two different grades</span> */}
Remove the commented block.

2023-09-07 12:23 UTC, ayotidapo commented on app/globals.css
leave the background color as it is in the global.scss file, you can give the homepage its own container background color

2023-09-07 12:52 UTC, ayotidapo requested changes
a

2023-09-07 12:55 UTC, ayotidapo requested changes

2023-09-07 12:55 UTC, ayotidapo commented on app/globals.css
> +  background: white;
leave the background color as it is in the global.scss file, you can give the homepage its own container background color

2023-09-07 13:07 UTC, ayotidapo requested changes

2023-09-07 13:07 UTC, ayotidapo commented on common/Desc/Desc.scss
> +  /* spacing {
and !important too

2023-09-07 13:07 UTC, ayotidapo commented on common/Footer/Footer.scss
> +  background-color: #c505cc !important;
lets agree on @onyegood suggestion of using var for colors and avoiding !important

2023-09-07 13:07 UTC, ayotidapo commented on common/homeNavbar/Navber.scss
> +  background-color: white !important;
!important... Mbah!

2023-09-07 13:07 UTC, ayotidapo commented on common/homeNavbar/index.tsx
> +          <Button className='sign-in-btn font-bol w-1.5 rounded  shadow-lg'>Sign in</Button>
is font-bol tailwind? I hope its not typo

2023-09-07 13:07 UTC, ayotidapo commented on common/plans/Plans.scss
> +  background-color: white !important;
lets avoid or totally not use !important

2023-09-07 13:07 UTC, ayotidapo commented on common/plans/index.tsx
> +            <div className='rounded-lg bg-[#EF03F8] p-4 shadow-md'>
Any tailwind custom properties used more than 2 times means its important and might likely to be used later lets start adding it to our tailwind extends configuration or better still add it to css variable, either of the two ways is fine

2023-09-07 14:13 UTC, victory-nwawunze commented on public/assets/linked in.svg
I have removed the space in all images.

2023-09-07 14:17 UTC, victory-nwawunze commented on public/assets/facebook icon.svg
I have changed the asset name to Facebook.

2023-09-07 15:19 UTC, victory-nwawunze commented on common/Footer/index.tsx
> +                <Image src='/assets/instagram.svg' width={60} height={40} alt='instagram' />
It is now reusable, passed in a couple of props and I map over all socialMedia icons.

2023-09-07 15:33 UTC, victory-nwawunze commented on common/homeNavbar/Navber.scss
> +  background-color: white !important;
i have Remove the important

2023-09-07 15:35 UTC, victory-nwawunze commented on common/homeNavbar/index.tsx
> +          <Button className='sign-in-btn font-bol w-1.5 rounded  shadow-lg'>Sign in</Button>
It was a typo, i have correct it.

2023-09-07 16:34 UTC, victory-nwawunze commented on common/Footer/Footer.scss
Have removed all important in the css

2023-09-07 16:46 UTC, victory-nwawunze commented on common/plans/Plans.scss
> +  background-color: white !important;
i Have removed !important ineverywhere in the app.

2023-09-07 17:37 UTC, victory-nwawunze commented on package.json
i Have uninstalled react-icon

2023-09-08 08:36 UTC, victory-nwawunze commented on common/Footer/Footer.scss
all styles are now reusable.

2023-09-08 08:37 UTC, victory-nwawunze commented on common/Footer/Footer.scss
Updated some SCSS styles to tailwind CSS.

2023-09-08 12:12 UTC, closed without merging